services:
  db:
    container_name: crypto_postgres
    image: postgres:17.6
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - crypto-data:/var/lib/postgresql/data
      - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
    networks:
      - crypto_network

  af:
    container_name: crypto_airflow
    image: apache/airflow:3.1.7
    ports:
      - "${AIRFLOW_PORT}:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db/airflow_db
    volumes:
      - ./config:/opt/airflow/config
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./output:/opt/airflow/output
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - crypto_network
    command:
      bash -c "airflow db migrate && airflow standalone"

volumes:
  crypto-data:
    driver: local

networks:
  crypto_network:
    driver: bridge
